id: 7918339899a041ffa08de208a1f4fde8
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_147-The_Teaching_on_the_Great_Compassion_of_the_Tathagata-v1
  language: bo
  author: ''
  volume: {}
